spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    # 配置druid数据源，否则MybatisConfig找不到DataSource
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 1111
logging:
  level:
    root: warn
    com:
      chendehe: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info


