spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    # 配置druid数据源，否则MybatisConfig找不到DataSource
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 5
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    async-init: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    cluster:
#      enable: true
#      nodes:
#        - 127.0.0.1:7379
#        - 127.0.0.1:7380
#    sentinel:
#      master: master
#      nodes:
#        - 127.0.0.1:7380
#    redisson:
#      config: classpath:redisson.yml

server:
  port: 1111
logging:
  level:
    root: warn
    com:
      chendehe: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info


